permalink: /:year/:month/:day/:title.html
paginate: 10
# markdown: rdiscount
markdown: kramdown

# 作者信息
author: 
  name: 李乾坤
  email: qiankun.li@qq.com
  link: 
  weibo: 
  github: http://qiankunli.github.io

# 站点信息
title: 李乾坤的博客 
description: 李乾坤的博客
url: http://qiankunli.github.io
rss_url: 

# gavatar头像及Favicon
gavatar: /public/upload/gavatar/gavatar.jpg
favicon: /public/upload/gavatar/favicon.ico

# google analytics 设置
google_analytics_tracking_id: UA-108442533-1
ga:
  id: UA-108442533-1
  url: 

# disqus 设置
disqus:
  shortname: qiankunli

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Docker
  - Java

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
